# Generated by Django 5.2.2 on 2025-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogzonereport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogzonereport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
