# Generated by Django 5.2.2 on 2025-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_dogzonereport_latitude_dogzonereport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogzonereport',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dogzonereport',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
